@host = http://localhost:5109
@productId = 1

### Obtener todos los productos
GET {{host}}/api/products
Accept: application/json

### Obtener un producto por ID
GET {{host}}/api/products/{{productId}}
Accept: application/json

### Crear un nuevo producto
POST {{host}}/api/products
Content-Type: application/json

{
    "name": "Apple",
    "price": 0.5,
    "description": "A fresh red apple"
}

### Actualizar un producto existente
PUT {{host}}/api/products/{{productId}}
Content-Type: application/json

{
    "name": "Producto Actualizado",
    "price": 0.6,
    "description": "Una descripción actualizada"
}

### Eliminar un producto
DELETE {{host}}/api/products/{{productId}}
Accept: application/json
